db:
  driver : com.mysql.cj.jdbc.Driver
  master:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url : jdbc:mysql://localhost:3306/poc_id_generator?characterEncoding=UTF-8&amp;useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username : mysql
    password : mysql
    hikari:
      idle-timeout: 10000
      pool-size : 10
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hbm2ddlAuto : create
      showSql: true
      formatSql: true
